name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: C1
      id: c1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: C1
        setup-command: pip install pytest pydantic
        command: pytest tests/test_lab.py -k "test_execution"
        timeout: 10
        max-score: 40
    - name: 'Criteria 2: Observability'
      id: criteria-2-observability
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Criteria 2: Observability'
        setup-command: ''
        command: pytest tests/test_lab.py -k "test_observability"
        timeout: 10
        max-score: 20
    - name: 'Criteria 3: Harmonization'
      id: criteria-3-harmonization
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Criteria 3: Harmonization'
        setup-command: ''
        command: pytest tests/test_lab.py -k "test_harmonization"
        timeout: 10
        max-score: 30
    - name: 'Criteria 4: Final Result'
      id: criteria-4-final-result
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Criteria 4: Final Result'
        setup-command: ''
        command: pytest tests/test_lab.py -k "test_final_output"
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        C1_RESULTS: "${{steps.c1.outputs.result}}"
        CRITERIA-2-OBSERVABILITY_RESULTS: "${{steps.criteria-2-observability.outputs.result}}"
        CRITERIA-3-HARMONIZATION_RESULTS: "${{steps.criteria-3-harmonization.outputs.result}}"
        CRITERIA-4-FINAL-RESULT_RESULTS: "${{steps.criteria-4-final-result.outputs.result}}"
      with:
        runners: c1,criteria-2-observability,criteria-3-harmonization,criteria-4-final-result
